shutdown_costmaps: false


### replanning
controller_frequency: 5.0   # run controller at 5.0 Hz
controller_patience: 5.0    # if the controller failed, clear obstacles and retry; after 5.0 s, abort and replan

planner_frequency: 0.0       # don't continually replan (only when controller failed)
planner_patience: 5.0        # if the first planning attempt failed, abort planning retries after 5.0 s...
max_planning_retries: 10     # ... or after 10 attempts (whichever happens first)
oscillation_timeout: 10.0    # abort controller and trigger recovery behaviors after 10.0 s
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "navfn/NavfnROS" #alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner


